services:
  hello-fruit-static-html-small-api:
    build:
      context: ../../../..
      dockerfile: examples/hello-fruit/server/static-html-small-api/Dockerfile
    environment:
      OPENRECEIVE_DEMO_MODE: ${OPENRECEIVE_DEMO_MODE:-test_nwc}
      PORT: "3001"
    expose:
      - "3001"
    volumes:
      - ../../../../openreceive.yml:/app/examples/hello-fruit/server/static-html-small-api/openreceive.yml:ro
      - openreceive-static-html-small-api-openreceive:/app/examples/hello-fruit/server/static-html-small-api/.openreceive

volumes:
  openreceive-static-html-small-api-openreceive:
