services:
  hello-fruit-static-html-small-api:
    build:
      context: ../../../..
      dockerfile: examples/hello-fruit/server/static-html-small-api/Dockerfile
    environment:
      OPENRECEIVE_DEMO_MODE: ${OPENRECEIVE_DEMO_MODE:-test_nwc}
      PORT: "3001"
    env_file:
      - ../../../../.env
    expose:
      - "3001"
