# Generated by Django 6.1.1 on 2026-09-07 03:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'shop_users',
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price_cents', models.IntegerField()),
                ('position', models.IntegerField(default=0)),
                ('image_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shop_products',
                'ordering': ['position', 'price_cents'],
                'indexes': [models.Index(fields=['active', 'position'], name='shop_products_active_pos_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price_cents__gt', 0)), name='shop_products_price_cents_check')],
            },
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(default='awaiting_payment', max_length=32)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_cents', models.IntegerField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.shopuser')),
            ],
            options={
                'db_table': 'shop_orders',
            },
        ),
        migrations.CreateModel(
            name='ShopOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('unit_price_cents', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.shoporder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.shopproduct')),
            ],
            options={
                'db_table': 'shop_order_items',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('shop_order', 'sku'), name='shop_order_items_order_sku_uniq'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='shop_order_items_quantity_check'), models.CheckConstraint(condition=models.Q(('unit_price_cents__gt', 0)), name='shop_order_items_unit_price_cents_check')],
            },
        ),
        migrations.AddIndex(
            model_name='shoporder',
            index=models.Index(fields=['state', 'created_at'], name='shop_orders_state_created_idx'),
        ),
        migrations.AddIndex(
            model_name='shoporder',
            index=models.Index(fields=['state', 'paid_at'], name='shop_orders_state_paid_idx'),
        ),
        migrations.AddConstraint(
            model_name='shoporder',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['awaiting_payment', 'paid'])), name='shop_orders_state_check'),
        ),
        migrations.AddConstraint(
            model_name='shoporder',
            constraint=models.CheckConstraint(condition=models.Q(('total_cents__gt', 0)), name='shop_orders_total_cents_check'),
        ),
    ]
