<?php

declare(strict_types=1);

namespace App\OpenReceive;

use App\Models\ShopOrder;
use App\Support\Visitor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use OpenReceive\Host as OpenReceiveHost;
use OpenReceive\PaymentSettlement;
use OpenReceive\Server\AuthorizeContext;

/**
 * Generated by `php artisan openreceive:install`, then filled in for the button
 * shop. THE THREE METHODS BELOW ARE THE ONLY BRIDGE between the engine and this
 * application's data: OpenReceive never sees ShopOrder, ShopProduct, ShopUser,
 * the cart or the download. If a future change to this demo needs a fourth
 * hook, that is a signal the boundary moved, and it is worth stopping over.
 */
final class Host implements OpenReceiveHost
{
    /**
     * THE HOST AUTHORIZES EVERY REQUEST; OpenReceive mints no tokens.
     *
     * `$context->request` is the Illuminate request — the same object a
     * controller gets, cookies decrypted by the `web` middleware group. This
     * shop's policy: an order id is a uuid, so it is not enumerable, but it
     * travels in every request body the payer's browser sends, so possession
     * of one is a CLAIM, not proof. The order has to belong to THIS browser,
     * which is the same check ShopController makes on its own routes.
     */
    public function authorize(AuthorizeContext $context): bool
    {
        $request = $context->request;
        if (!$request instanceof Request) {
            return false;
        }
        $order = ShopOrder::findByReference($context->reference());
        if ($order === null) {
            return false;
        }
        $visitorId = Visitor::idFrom($request);
        return $visitorId !== null && $order->shop_user_id === $visitorId;
    }

    /**
     * The price for a reference — here the ShopOrder id — read from OUR OWN
     * ROW. Nothing a payer sends can reach this number: the create body cannot
     * carry an amount at all. null means there is nothing to pay for (a 404).
     *
     * `value` is a decimal STRING formatted from integer cents. Never a float.
     * `description` is what the payer is BUYING, in our own words — the one
     * line the checkout renders above the amount.
     */
    public function amountFor(string $reference): ?array
    {
        $order = ShopOrder::findByReference($reference);
        if ($order === null) {
            return null;
        }
        return [
            'currency' => $order->currency,
            'value' => $order->totalAmount(),
            'description' => $order->checkoutDescription(),
        ];
    }

    /**
     * Runs INSIDE the settlement transaction, only for the order's first
     * settled attempt. Across every settlement path OpenReceive owns this runs
     * AT MOST ONCE per reference; what it cannot see is a second fulfillment
     * path of OURS, so the transition is still the guarded conditional UPDATE
     * in ShopOrder::claimPaid — the WHERE clause is the lock.
     *
     * Fulfillment for a virtual product: flipping the order to `paid` IS the
     * delivery, because ShopController::download serves the artwork only from
     * a paid row. DATABASE WRITES ONLY in here: the Eloquent UPDATE runs on the
     * same PDO the engine's transaction holds, so the order transition and the
     * payment record commit together. A log line is the only side effect.
     */
    public function onPaid(PaymentSettlement $settlement): void
    {
        $claimed = ShopOrder::claimPaid($settlement->reference, $settlement->paidAt, $settlement->paymentHash);
        if (!$claimed) {
            return;
        }
        Log::info('[buttons-laravel] openreceive.on_paid: checkout settled — the order is paid and its downloads unlocked.', [
            'reference' => $settlement->reference,
            'payment_hash' => $settlement->paymentHash,
        ]);
    }
}
