// Source-shape tripwires: rules about how the React package is written that no rendered
// output can express. Behavior that CAN be rendered is asserted in
// tests/react-checkout-behavior.test.mjs instead — regex-matching effect dependency
// arrays passed while the behavior they claimed to protect was broken.
import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";

const REACT_SRC_DIR = path.join(process.cwd(), "packages/js/react/src");
// The react package source is split across logical modules; read them all so
// structure assertions stay location-agnostic across future refactors.
function readReactSource() {
  return readdirSync(REACT_SRC_DIR)
    .filter((file) => file.endsWith(".ts"))
    .sort()
    .map((file) => readFileSync(path.join(REACT_SRC_DIR, file), "utf8"))
    .join("\n");
}

test("source-shape tripwire: copy feedback goes through the shared controller", () => {
  // The one contract no rendered output can express: transient copy feedback is
  // owned by the shared controller, never by ad-hoc timers scattered per
  // component (which drift apart and leak across unmounts). The visible
  // behavior (label flips, then resets) is covered by the rendered
  // copy-feedback test in tests/react-checkout-behavior.test.mjs, and
  // controller-restart behavior for unstable host callbacks (logger/onError/
  // onState/onSettled/refreshStatus) is covered behaviorally there too.
  const source = readReactSource();

  assert.match(source, /createOpenReceiveTransientFeedbackController/);
  assert.doesNotMatch(source, /globalThis\.setTimeout/);
});

test("React package exposes shared browser-owned checkout styles", () => {
  const manifest = JSON.parse(
    readFileSync(path.join(process.cwd(), "packages/js/react/package.json"), "utf8"),
  );
  const browserStyles = readFileSync(
    path.join(process.cwd(), "packages/js/browser/src/styles.css"),
    "utf8",
  );
  const reactStyles = readFileSync(
    path.join(process.cwd(), "packages/js/react/src/styles.css"),
    "utf8",
  );

  assert.equal(manifest.exports["./styles.css"], "./dist/styles.css");
  assert.match(browserStyles, /\.btn|@layer/);
  assert.match(reactStyles, /Generated by tools\/package\/build-browser-css\.mjs/);
});
