services:
  hello-fruit-node-express:
    build:
      context: ../../../..
      dockerfile: examples/hello-fruit/server/node-express/Dockerfile
    environment:
      PORT: "3000"
    env_file:
      - ../../../../.env
    expose:
      - "3000"
