# frozen_string_literal: true

# Configure during initializer load (not after_initialize). `parent_controller`
# is read when OpenReceive::ApplicationController is eager-loaded in production,
# which happens before after_initialize hooks run.
#
# Generated by `bin/rails generate openreceive:install`, then filled in for the
# button shop. THE THREE HOOKS BELOW ARE THE ONLY BRIDGE between the engine and
# this application's data: OpenReceive never sees ShopOrder, ShopProduct,
# ShopUser, the cart, or the download. If a future change to this demo needs a
# fourth hook, that is a signal the boundary moved, and it is worth stopping
# over.
require Rails.root.join("lib/button_shop/testkit")

OpenReceive.configure do |config|
  config.parent_controller = "ApplicationController"
  # Secrets load from NWC_URI, LSC_URI_PRIMARY, and LSC_URI_BACKUP.
  # Keep ordinary settings here in the Rails initializer.
  config.price_currencies = ["USD"]

  # TESTKIT WALLET MODE, and the only branch in this file.
  #
  # `DEMO_WALLET=testkit` replaces THREE THINGS — the wallet, the swap provider
  # and the price feed — with in-memory fakes, so the whole shop can be clicked
  # through (Lightning, a swap deposit, a refund) with no NWC_URI, no
  # FixedFloat keys and no network. Everything else on this page is the
  # production wiring: the three hooks below, the engine, the migrations, the
  # controllers and ActionCable all run exactly as they do in compose.
  #
  # That is the whole value of it. A test lane that also swapped the engine
  # would prove the fakes work; this one proves the integration does. See
  # lib/button_shop/testkit.rb.
  if ButtonShop::Testkit.enabled?
    config.nwc_client = ButtonShop::Testkit.wallet
    config.swap_providers = [ButtonShop::Testkit.swap_provider]
    # BTC at a fixed $50,000, the same constant the JS StaticPriceProvider
    # uses, so a $1.00 button is 2,000 sats on every stack.
    config.price_provider = OpenReceive::Rates::StaticPriceProvider.new
  else
    # Built-in cached live BTC/USD feed (a CoinGecko-compatible primary plus the
    # OpenReceive fallback mirror). OPENRECEIVE_PRICE_FEED_*_URL env vars override
    # the URLs for dev and test.
    config.price_provider = OpenReceive::Rates.create_cached_live_price_feed(
      currencies: ["USD"],
      **OpenReceive::Rates.read_price_feed_url_overrides(ENV)
    )
  end

  # THE HOST AUTHORIZES EVERY REQUEST; OpenReceive mints no tokens.
  #
  # `context` is a Hash with three symbol keys:
  #   context[:action]   — which route: "checkout.prepare", "checkout.create",
  #                        "payment.check", "swap.quote", "swap.create",
  #                        "swap.read", or "swap.refund"
  #   context[:request]  — the ActionDispatch::Request; read your session,
  #                        cookies, or headers from it, as in a controller
  #   context[:resource] — { reference:, payment_hash: } copied from the
  #                        payer's JSON body. It NAMES an order; it does not
  #                        prove this caller owns it.
  # Return true to allow the request, false for a 403.
  #
  # This shop's policy: an order id is a uuid, so it is not enumerable — but it
  # travels in every request body the payer's browser sends, so possession of
  # one is a claim, not proof. The order has to belong to THIS browser, which is
  # the same check ShopController makes on its own routes.
  #
  # The cookie is read straight off the request. `cookie_jar` is available on
  # ActionDispatch::Request, and `.signed` verifies against the app's key
  # generator — the same jar `cookies.signed` gives a controller, because the
  # engine's requests travel the host's full middleware stack. A tampered value
  # fails the signature and reads as nil, which lands in the same `false` as a
  # missing one.
  config.authorize = lambda do |context|
    order = ShopOrder.find_by_reference(context[:resource][:reference])
    next false unless order

    visitor_id = context[:request].cookie_jar.signed[ShopIdentity::COOKIE]
    visitor_id.present? && order.shop_user_id.to_s == visitor_id.to_s
  end

  # The price for a reference — here the ShopOrder id — read from our own row.
  # Nothing a payer sends can reach this number: the create body cannot carry an
  # amount at all. nil means there is nothing to pay for (a 404).
  #
  # `value` is a decimal STRING formatted from integer cents. Never a float.
  #
  # `description` beside the price is what the payer is BUYING, in our own
  # words — one display string the checkout renders above the amount. Without it
  # the payer sees a QR code and "$4.00" and no sign of what the four dollars is
  # for; OpenReceive owns no line items, so this is the whole of what it can
  # show on its own.
  config.amount_for = lambda do |reference|
    order = ShopOrder.find_by_reference(reference)
    next nil unless order

    {
      currency: order.currency,
      value: order.total_amount,
      description: order.checkout_description
    }
  end

  # Runs INSIDE the settlement transaction, only for the order's first settled
  # attempt. `settlement` exposes reference, payment_hash, and paid_at.
  #
  # Across every settlement path OpenReceive owns (wallet notifications, the
  # opportunistic reconcile pass, an explicit reconcile job) this runs AT MOST
  # ONCE per reference — a second payment to a second invoice for the same order
  # is recorded with status_reason = 'duplicate_settlement' and never fulfills
  # again. What OpenReceive cannot see is a second fulfillment path of OUR own,
  # so the transition is still written as the guarded conditional UPDATE in
  # ShopOrder.claim_paid! — the WHERE clause is the lock.
  #
  # Fulfillment for a virtual product: flipping the order to `paid` IS the
  # delivery, because ShopController#download serves the artwork only from a
  # paid row.
  #
  # DATABASE WRITES ONLY, inside the hook. An email, a webhook or an ActionCable
  # broadcast sent from here would survive a rollback: the payer's browser would
  # be told about an order that no longer exists, and the public feed would be
  # told to re-read a row that was never committed.
  #
  # So the settlement PUSH is scheduled rather than sent.
  # `ActiveRecord.after_all_transactions_commit` runs its block once the
  # outermost transaction has actually committed — and immediately when there is
  # no open transaction, so it is correct on both paths. Only the caller that
  # WON the guarded UPDATE schedules anything, so a duplicate settlement is
  # silent.
  config.on_paid = lambda do |settlement|
    claimed = ShopOrder.claim_paid!(
      reference: settlement.reference,
      paid_at: Time.at(settlement.paid_at).utc,
      payment_hash: settlement.payment_hash
    )
    next false unless claimed

    ActiveRecord.after_all_transactions_commit do
      # Re-read rather than closing over a stale object: this runs after the
      # commit, and the row is the authority for what to say about it.
      ShopOrder.find_by_reference(settlement.reference)&.broadcast_settled!
    end

    true
  end

  # Cap invoice creation per client IP, counted from the engine-owned
  # openreceive_payments rows. On here because this is a public web shop and
  # every payer arrives on their own address. Behind a proxy, configure Rails'
  # trusted proxies so request.ip is the payer, not the proxy.
  config.rate_limiting = true

  # Settlement discovery is opportunistic by default: every engine request first
  # runs one reconcile pass through the durable openreceive_meta gate (shared by
  # all Puma workers; min 2s between real wallet scans), so pending attempts
  # settle or close on any later OpenReceive call — no scheduled job required.
  # Set false only if a dedicated worker owns scanning.
  # config.opportunistic_reconcile = false
end

# Optional: for push settlement the moment the wallet reports payment_received,
# run the long-lived worker `bin/rails openreceive:notifications` — it listens
# for NWC-02 notifications AND reconciles periodically in the same process (the
# safety net for notifications missed while it was down). compose.yml runs
# exactly one of those, as the `notifications` service.
