//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("BTCPayServer.Plugins.OpenReceive")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyDescriptionAttribute(("Receive Lightning payments into your own wallet with a receive-only NWC code, and" +
    " accept USDT, USDC, ETH and SOL through a Lightning Swap Connect provider."))]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.4.3.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.4.3+5a00744ae0726b0e91778ebce66db20394cb731f")]
[assembly: System.Reflection.AssemblyProductAttribute("OpenReceive")]
[assembly: System.Reflection.AssemblyTitleAttribute("BTCPayServer.Plugins.OpenReceive")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.4.3.0")]

// Generated by the MSBuild WriteCodeFragment class.

