source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 7.1"
gem "puma", "~> 6.4"
gem "sqlite3", "~> 1.7"
gem "openreceive", path: "../../../../packages/ruby/openreceive"
gem "openreceive-rails", path: "../../../../packages/ruby/openreceive-rails"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end
