//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("OpenReceive.IntegrationTests")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+8fcdb48b900b80ad45497f09ede348ed6c35f39a")]
[assembly: System.Reflection.AssemblyProductAttribute("OpenReceive.IntegrationTests")]
[assembly: System.Reflection.AssemblyTitleAttribute("OpenReceive.IntegrationTests")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyMetadata("Microsoft.Testing.Platform.Application", "true")]

// Generated by the MSBuild WriteCodeFragment class.

