"""`manage.py openreceive_install <app_label>` — write `<app>/openreceive_host.py`
(the three hooks with the generated placeholders wired, plus the exactly-once
fulfillment note) and PRINT the settings and urls lines to add. It edits no
settings.py and no urls.py: those files are the host's, and a generator that
rewrites them is the thing people stop trusting. Twin of the Rails
`openreceive:install` generator and the JS scaffold."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from django.apps import apps
from django.core.management.base import BaseCommand, CommandError, CommandParser

from openreceive._generated.fulfillment_note import FULFILLMENT_NOTE_TEMPLATE

HOST_FILE = "openreceive_host.py"


def fulfillment_note(prefix: str = "# ", table: str = "openreceive_payments") -> str:
    """The shared note with every line prefixed; blank lines drop the prefix's
    trailing space so no comment block ends in trailing whitespace."""
    return "\n".join(
        prefix.rstrip() if not line else f"{prefix}{line.replace('{{table}}', table)}"
        for line in FULFILLMENT_NOTE_TEMPLATE
    )


def render_host_module(app_label: str) -> str:
    note = fulfillment_note("    # ")
    return f'''"""OpenReceive host hooks for the `{app_label}` app.

Generated by `manage.py openreceive_install {app_label}`. THE THREE METHODS BELOW ARE
THE ONLY BRIDGE between the OpenReceive engine and this application's data:
OpenReceive never sees your orders, users, prices or fulfillment. Point
settings at this class:

    OPENRECEIVE = {{"HOST": "{app_label}.openreceive_host.Host"}}
"""

from __future__ import annotations

from typing import Any

from openreceive.server import ALLOW_ALL_AUTHORIZE, LOGGING_ON_PAID, HookContext
from openreceive.storage import PaymentSettlement


class Host:
    # THE HOST AUTHORIZES EVERY REQUEST; OpenReceive mints no tokens.
    #
    # `context` has three attributes:
    #   context.action    — which route: "checkout.prepare", "checkout.create",
    #                       "payment.check", "swap.quote", "swap.create",
    #                       "swap.read", or "swap.refund"
    #   context.request   — the django.http.HttpRequest; read request.user,
    #                       request.session or cookies from it, as in a view
    #   context.resource  — {{"reference": ..., "payment_hash": ...}} copied from
    #                       the payer's JSON body. It names an order; it does
    #                       not prove this caller owns it. reference is always a
    #                       validated non-empty str (<= 200 chars); payment_hash
    #                       is absent except on payment.check / swap.read /
    #                       swap.refund.
    # Return True to allow the request, False for a 403.
    #
    # The default below is a NAMED PLACEHOLDER, and `manage.py check` warns
    # (openreceive.W002) for as long as it is still here. It allows every
    # request, treating possession of the reference as the authorization (an
    # unknown reference is still a 404, because amount_for returns None for
    # it). That is only safe while your references are unguessable (UUIDs, not
    # sequential integers). If they are enumerable, or an order should only be
    # visible to the customer who placed it, check ownership against your own
    # session instead (`Order` stands in for your own model — any name works;
    # OpenReceive never sees it):
    #
    #     def authorize(self, context: HookContext) -> bool:
    #         order = Order.objects.filter(pk=context.resource["reference"]).first()
    #         return order is not None and order.user_id == context.request.user.id
    authorize = staticmethod(ALLOW_ALL_AUTHORIZE)

    # The price for a reference — the string your checkout passes, typically
    # your order id. Your application is the only price authority; payer input
    # never carries an amount. Return {{"currency": "USD", "value": "12.00"}} or
    # {{"sats": 1200}}, or None when there is nothing to pay for (a 404). `value`
    # is a decimal STRING from your own row, never a float.
    #
    # An optional "description" beside the price is what the payer is BUYING,
    # in your own words — one display string the checkout renders above the
    # amount. Without it the payer sees a QR and a number and no sign of what
    # the number is for; OpenReceive owns no line items, so this is the whole
    # of what it can show on its own.
    def amount_for(self, reference: str) -> dict[str, Any] | None:
        # TODO(price): look the reference up in your own application, e.g.
        #     order = Order.objects.filter(pk=reference).first()
        #     if order is None:
        #         return None
        #     return {{"currency": "USD", "value": str(order.total),
        #             "description": f"{{order.items.count()}} items"}}
        raise NotImplementedError(
            "{app_label}/openreceive_host.py: amount_for must read the price for "
            f"reference {{reference!r}} from your own order model. "
            "https://openreceive.org/guides/quickstart-django.md"
        )

    # Runs INSIDE the settlement transaction (the engine wraps it in
    # transaction.atomic()), only for the order's first settled attempt.
    # `settlement` exposes reference, payment_hash, paid_at (unix seconds) and
    # details; `settlement.connection` is None under the ORM — use plain
    # QuerySet calls.
    #
{note}
    #
    # TODO(fulfillment): replace the logging placeholder with your real
    # fulfillment, written as the guarded transition described above so a
    # second fulfillment path can never ship the same order twice
    # (FulfillOrder stands in for your own application code — ship the goods,
    # enqueue the confirmation email. OpenReceive does not provide it):
    #
    #     def on_paid(self, settlement: PaymentSettlement) -> None:
    #         claimed = Order.objects.filter(
    #             pk=settlement.reference, state="awaiting_payment"
    #         ).update(state="paid", paid_at=datetime.fromtimestamp(settlement.paid_at, tz=UTC))
    #         if claimed == 0:
    #             return  # someone else already fulfilled it
    #         FulfillOrder.run(settlement.reference, payment_hash=settlement.payment_hash)
    #
    # The placeholder only logs the settlement; `manage.py check` warns
    # (openreceive.W001) while it is still configured, because orders would
    # otherwise be recorded as settled without ever being fulfilled.
    on_paid = staticmethod(LOGGING_ON_PAID)

    # Optional: runs AFTER the settlement transaction committed, once, for the
    # same first settled attempt. The place for an email, a webhook or a
    # channels broadcast — anything that must not survive a rollback.
    #
    #     def after_paid(self, settlement: PaymentSettlement) -> None:
    #         send_receipt.delay(settlement.reference)
'''


def settings_instructions(app_label: str) -> str:
    return f"""
Add to settings.py:

    INSTALLED_APPS += ["openreceive.django"]

    OPENRECEIVE = {{
        "HOST": "{app_label}.openreceive_host.Host",
        "PRICE_CURRENCIES": ["USD"],
        # Recommended for public web shops: cap invoice creation per client IP,
        # counted from the engine-owned openreceive_payments rows. Leave it off
        # for point-of-sale deployments where many payers share one IP.
        "RATE_LIMITING": False,
        # Settlement discovery is opportunistic by default: every OpenReceive
        # request first runs one reconcile pass through the durable
        # openreceive_meta gate (shared by every worker; min 2s between real
        # wallet scans). Set False only if a dedicated worker owns scanning.
        "OPPORTUNISTIC_RECONCILE": True,
    }}

Add to urls.py:

    from django.urls import include, path
    urlpatterns += [path("openreceive/", include("openreceive.django.urls"))]

Then:

    manage.py migrate                      # creates openreceive_payments + openreceive_meta
    export NWC_URI=<receive-only NWC code> # Django loads no .env; the server environment must carry it
    manage.py openreceive_doctor           # reports the install state, never prints a secret

Secrets load from NWC_URI, LSC_URI_PRIMARY and LSC_URI_BACKUP in os.environ.
Optional push settlement: run `manage.py openreceive_notifications` as one long-lived process.
"""


class Command(BaseCommand):
    help = (
        "Write <app>/openreceive_host.py with the three host hooks and print the settings "
        "and urls lines to add. Edits no settings.py."
    )

    def add_arguments(self, parser: CommandParser) -> None:
        parser.add_argument("app_label", help="The installed app that will own openreceive_host.py")
        parser.add_argument(
            "--path",
            default=None,
            help="Directory to write into (default: the app's own directory)",
        )
        parser.add_argument(
            "--force", action="store_true", help="Overwrite an existing openreceive_host.py"
        )

    def handle(self, *args: Any, **options: Any) -> None:
        app_label = str(options["app_label"])
        try:
            app_config = apps.get_app_config(app_label)
        except LookupError as error:
            raise CommandError(
                f"No installed app with label {app_label!r} ({error}). Pass the app_label of "
                "the app that should own the hooks."
            )
        directory = Path(options["path"]) if options["path"] else Path(app_config.path)
        target = directory / HOST_FILE
        if target.exists() and not options["force"]:
            raise CommandError(f"{target} already exists; pass --force to overwrite it.")
        directory.mkdir(parents=True, exist_ok=True)
        target.write_text(render_host_module(app_label), encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"Wrote {target}"))
        self.stdout.write(settings_instructions(app_label))
