/**
 * Shared daisyUI / Tailwind class strings for OpenReceive checkout UI.
 * Kept as string constants so Tailwind can scan them for the prebuilt stylesheet.
 */

export const orClasses = {
  root: "grid gap-3 min-w-0",
  paymentLayout:
    "grid gap-3 grid-cols-[auto_minmax(0,1fr)] gap-x-3 md:gap-x-5 items-start min-w-0",
  paymentLayoutExpired: "grid gap-3 grid-cols-1 items-start min-w-0",
  lightningPane: "grid gap-2 items-start justify-items-start min-w-0",
  qr: "justify-self-start w-[min(148px,38vw)] md:w-[min(200px,36vw)] [&_svg]:block [&_svg]:w-full [&_svg]:h-auto",
  satsDetail:
    "text-base-content/60 text-sm leading-snug justify-self-start max-w-[min(148px,38vw)] md:max-w-[min(200px,36vw)]",
  invoiceTitle: "m-0 text-sm font-semibold leading-tight",
  paymentInfo: "grid gap-1.5 min-w-0 content-start",
  meta: "flex flex-wrap gap-1.5 items-center",
  metaItem: "badge badge-ghost badge-sm min-h-6",
  stateSettled: "badge badge-success badge-sm",
  statePending: "badge badge-ghost badge-sm",
  actions: "flex flex-wrap gap-2 justify-start",
  btn: "btn",
  btnGhost: "btn btn-ghost",
  btnSoft: "btn btn-soft",
  btnBlock: "btn btn-block",
  btnSm: "btn btn-sm",
  btnSquare: "btn btn-square btn-sm",
  copyIcon: "shrink-0 size-4",
  themeToggle: "btn btn-ghost btn-sm gap-2 justify-self-end",
  textarea: "textarea textarea-bordered w-full font-mono text-sm min-h-[86px]",
  paymentStatus: "flex items-center gap-2.5 min-w-0",
  paymentStatusBody: "grid gap-0.5 min-w-0 flex-1",
  paymentStatusTitle: "text-base font-semibold leading-tight min-w-0",
  paymentStatusDetail: "text-base-content/60 text-sm leading-snug",
  spinner: "loading loading-spinner loading-md text-warning",
  countdown: "text-base-content/60 text-sm",
  countdownStrong: "text-base-content font-semibold",
  creating: "grid gap-2 place-items-center p-4",
  wizard: "card card-border bg-base-200 grid gap-3 p-3",
  wizardHeader: "grid gap-0.5",
  wizardHeaderTitle: "text-lg font-bold m-0",
  wizardHeaderSubtitle: "text-base-content/60 text-sm m-0",
  methodGrid: "grid grid-cols-2 md:grid-cols-4 gap-2",
  methodCard:
    "card card-border bg-base-100 grid gap-1.5 content-start min-h-[120px] p-2.5 text-left cursor-pointer hover:border-primary",
  methodCardUnavailable:
    "card card-border bg-base-100 grid gap-1.5 content-start min-h-[120px] p-2.5 text-left opacity-50 cursor-not-allowed",
  methodCardStatic:
    "card card-border bg-base-100 grid gap-1.5 content-start min-h-[120px] p-2.5 text-left",
  methodCardReady:
    "card card-border bg-base-100 grid gap-1.5 content-start min-h-[120px] p-2.5 text-left cursor-pointer hover:border-primary",
  methodIcon: "size-10 aspect-square",
  methodTitle: "font-bold text-sm",
  methodDetail: "text-base-content/60 text-xs leading-snug",
  methodNetwork: "dropdown w-full",
  methodNetworkTrigger:
    "btn btn-sm btn-block justify-between gap-2 font-normal border border-base-300 bg-base-100",
  methodNetworkTriggerLabel: "inline-flex items-center gap-2 min-w-0",
  methodNetworkMenu:
    "dropdown-content menu menu-sm bg-base-100 rounded-box z-10 w-full p-1 shadow border border-base-300",
  methodNetworkOption: "gap-2",
  methodNetworkIcon: "size-4 shrink-0 aspect-square",
  methodConfirm: "btn btn-block btn-sm",
  breadcrumbs: "breadcrumbs text-sm",
  breadcrumbCurrent: "font-bold",
  routePicker: "grid grid-cols-2 md:grid-cols-4 gap-2",
  routeButton:
    "card card-border bg-base-100 grid gap-1.5 content-start min-h-[120px] p-2.5 text-left cursor-pointer hover:border-primary",
  routeButtonSelected:
    "card card-border bg-base-100 grid gap-1.5 content-start min-h-[120px] p-2.5 text-left border-primary ring-2 ring-primary/30",
  countrySelect: "inline-flex items-center gap-2 text-xs font-bold",
  countrySelectLabel: "sr-only",
  countrySelectControl: "select select-bordered select-sm max-w-[min(280px,100%)]",
  wizardResults: "grid gap-2.5",
  wizardEmpty: "alert",
  wizardRoute: "grid gap-3",
  wizardRouteHeading: "flex flex-wrap items-center gap-2",
  providerGrid: "grid grid-cols-1 md:grid-cols-2 gap-2",
  providerCard:
    "card card-border bg-base-100 p-3 grid gap-1 items-center grid-cols-[minmax(0,1fr)_auto] md:grid-cols-[minmax(0,1fr)_auto_auto]",
  providerCardRecommended:
    "card card-border bg-base-100 p-3 grid gap-1 items-center grid-cols-[minmax(0,1fr)_auto] md:grid-cols-[minmax(0,1fr)_auto_auto] border-warning ring-2 ring-warning/30",
  providerHeading: "flex gap-2 items-center min-w-0",
  providerIcon: "rounded size-7 shrink-0",
  providerName: "font-semibold truncate m-0 min-w-0",
  providerBadge: "badge badge-ghost badge-sm whitespace-nowrap",
  providerKind: "text-base-content/60 text-sm m-0",
  providerActions: "flex gap-2 items-center justify-self-end",
  providerOpen: "btn btn-soft btn-sm",
  swapActions: "grid gap-2.5 grid-cols-1 md:grid-cols-3",
  swapAction: "grid gap-2",
  swapEstimate: "text-base-content/60 m-0 text-sm",
  swapWarning: "alert alert-warning text-sm",
  swapProgress: "text-base-content/60 m-0",
  swapInstruction: "m-0 text-base-content text-base font-bold text-center md:text-left",
  swapStart: "btn",
  swapPanel: "grid gap-3",
  swapDepositLayout:
    "grid gap-3 md:grid-cols-[auto_minmax(0,1fr)] md:gap-x-5 md:items-start min-w-0",
  swapDepositSide: "grid gap-3 min-w-0 content-start",
  swapHeading: "flex flex-wrap gap-2 items-center justify-between",
  swapHeadingTitle: "text-lg font-semibold",
  swapHeadingDetail: "text-base-content/60",
  swapQr:
    "justify-self-center w-[min(200px,100%)] block h-auto md:justify-self-start md:w-[min(180px,100%)]",
  swapDetails: "grid gap-2 m-0",
  swapDetailsDt: "text-base-content/60 text-xs font-bold uppercase",
  swapDetailsDd: "grid gap-2 grid-cols-[minmax(0,1fr)_auto] items-center m-0",
  swapDetailsCode: "min-w-0 break-all font-mono text-sm",
  swapBreakdown: "grid gap-2 py-2 border-t border-base-300",
  swapBreakdownTitle: "m-0 text-base-content/60 text-xs font-bold uppercase",
  swapBreakdownRows: "grid grid-cols-[1fr_auto] gap-x-3 gap-y-1.5 items-baseline m-0",
  swapBreakdownNote: "m-0 text-base-content/60 text-xs",
  swapWaitingTitle: "flex items-baseline justify-between gap-3 min-w-0",
  swapCountdown: "shrink-0 text-base-content font-semibold tabular-nums",
  swapBack: "btn btn-sm justify-self-start",
  swapSupport: "collapse collapse-arrow bg-base-200",
  swapSupportTitle: "collapse-title font-bold min-h-0 py-2",
  swapSupportContent: "collapse-content",
  swapRefund: "grid gap-2",
  swapRefundInput: "input input-bordered w-full",
  tutorialModal: "modal modal-open",
  tutorialBox: "modal-box grid gap-3 max-w-[min(440px,100%)]",
  tutorialHeader: "flex gap-2 items-center justify-between",
  tutorialTitle: "flex items-center gap-2.5 min-w-0",
  tutorialHeaderLogo: "size-9 rounded shrink-0",
  tutorialClose: "btn btn-sm btn-square btn-ghost",
  tutorialFrame: "flex items-center justify-center min-h-0 overflow-hidden rounded-box border border-base-300 bg-base-200",
  tutorialImage: "block w-auto max-w-full h-auto max-h-[min(66vh,720px)] object-contain",
  tutorialCaption: "m-0 text-base font-bold text-center",
  tutorialIntro: "grid gap-3 p-4 text-center",
  tutorialProviderLogo: "justify-self-center size-[52px] rounded",
  tutorialCopy: "btn justify-self-center min-w-[min(240px,100%)]",
  tutorialCopyMessage: "text-success font-bold",
  tutorialProgress: "m-0 text-base-content/60 text-xs text-center",
  tutorialSteps: "flex gap-1.5 justify-center",
  tutorialStep: "badge badge-xs badge-ghost size-2 p-0",
  tutorialStepActive: "badge badge-xs badge-neutral size-2 p-0",
  tutorialControls: "grid grid-cols-2 gap-2",
  hostBridge: "block",
} as const;

export type OrClassKey = keyof typeof orClasses;
