import { assetUrl, lazyAssetUrlTable } from "./asset-url.ts";

// Generated by tools/provider-data/create-provider-v4.mjs — do not edit.
// One filename list drives the whole map; it mirrors the registry's
// icon_path references exactly (a test pins this list to the assets
// directory contents so they cannot drift).
export const OPENRECEIVE_PROVIDER_ICON_FILES: readonly string[] = [
  "aqua.png",
  "belo.png",
  "binance.png",
  "bipa.png",
  "bitfinex.png",
  "bitget.png",
  "bitnob.png",
  "bitso.png",
  "bity.png",
  "blink.png",
  "bluewallet.png",
  "boltz.png",
  "bringin.png",
  "bullbitcoin.png",
  "cashapp.png",
  "chivo.png",
  "coinbase.png",
  "coincorner.png",
  "fixedfloat.png",
  "getalby.png",
  "kraken.png",
  "kryptex.png",
  "kucoin.png",
  "mtpelerin.png",
  "okcoin.png",
  "okx.png",
  "phoenix.png",
  "pouch.png",
  "ripio.png",
  "river.png",
  "rizful.png",
  "shakepay.png",
  "sideshift.png",
  "speed.png",
  "strike.png",
  "walletofsatoshi.png",
  "zeus.png",
];

// Lazy: an entry resolves when it is read, so a host that supplies an
// AssetUrlResolver (and therefore never reads one) gets no warning. See
// lazyAssetUrlTable.
export const providerIconUrls: Readonly<Record<string, string>> = lazyAssetUrlTable(
  OPENRECEIVE_PROVIDER_ICON_FILES.map((file) => `assets/provider-icons/${file}`),
  (key) => assetUrl(`./${key}`),
);
