import { assetUrl } from "./asset-url.ts";

// Generated by tools/provider-data/create-provider-v4.mjs — do not edit.
// One filename list drives the whole map, so a new icon dropped into
// assets/provider-icons only needs one entry here (a test pins this list to
// the directory contents so they cannot drift).
export const OPENRECEIVE_PROVIDER_ICON_FILES: readonly string[] = [
  "aqua.png",
  "belo.png",
  "binance.png",
  "bipa.png",
  "bitfinex.png",
  "bitget.png",
  "bitnob.png",
  "bitso.png",
  "bity.png",
  "blink.png",
  "bluewallet.png",
  "boltz.png",
  "bringin.png",
  "bullbitcoin.png",
  "cakewallet.png",
  "cashapp.png",
  "changenow.png",
  "chivo.png",
  "coinbase.png",
  "coincorner.png",
  "fixedfloat.png",
  "getalby.png",
  "kraken.png",
  "kryptex.png",
  "kucoin.png",
  "mtpelerin.png",
  "muun.png",
  "okcoin.png",
  "okx.png",
  "phoenix.png",
  "pouch.png",
  "ripio.png",
  "river.png",
  "rizful.png",
  "shakepay.png",
  "sideshift.png",
  "simpleswap.png",
  "speed.png",
  "strike.png",
  "trocador.png",
  "walletofsatoshi.png",
  "zeus.png",
];

export const openReceiveProviderIconUrls: Readonly<Record<string, string>> = Object.fromEntries(
  OPENRECEIVE_PROVIDER_ICON_FILES.map((file) => [
    `assets/provider-icons/${file}`,
    assetUrl(`./assets/provider-icons/${file}`),
  ]),
);
