import { drizzleOrderIdColumn, isSqlite } from "../shared.ts";
import type { ScaffoldFile, ScaffoldPaymentsOptions } from "../types.ts";
import { wiringGuideMarkdown } from "../wiring-guide.ts";

export function renderDrizzleFiles(options: ScaffoldPaymentsOptions): ScaffoldFile[] {
  const sqlite = isSqlite(options);
  const orderIdColumn = drizzleOrderIdColumn(options.orderIdType, options.dialect);
  const orderIdLine = options.skipForeignKey
    ? `orderId: ${orderIdColumn},`
    : `orderId: ${orderIdColumn}.references(() => ${camel(options.orderTable)}.id, { onDelete: "restrict" }),`;
  const ordersImportNote = options.skipForeignKey
    ? ""
    : `// Adjust the path to wherever your host schema defines \`${camel(options.orderTable)}\`
// (needed for the foreign key below), e.g.:
// import { ${camel(options.orderTable)} } from "./schema";\n`;

  const header = `// Generated by \`npx openreceive scaffold payments\` — schema only.
// OpenReceive owns the payment-attempt repository at runtime
// (createOpenReceiveHost in @openreceive/http); these two tables exist so
// \`drizzle-kit generate\` creates the canonical DDL. Keep every column.
// Timestamps are unix-seconds integer columns, on purpose.
`;

  const schema = sqlite
    ? `${header}import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
${ordersImportNote}
export const openReceivePayments = sqliteTable(
  "openreceive_payments",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    ${orderIdLine}
    paymentHash: text("payment_hash").notNull(),
    status: text("status").notNull().default("pending"),
    statusReason: text("status_reason"),
    paidAt: integer("paid_at"),
    expiresAt: integer("expires_at").notNull(),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
    insertedAt: integer("inserted_at").notNull(),
    checkoutData: text("checkout_data").notNull(),
    swapData: text("swap_data"),
    clientIp: text("client_ip"),
  },
  (table) => [
    uniqueIndex("openreceive_payments_hash_uidx").on(table.paymentHash),
    index("openreceive_payments_order_created_idx").on(table.orderId, table.createdAt),
    index("openreceive_payments_status_created_idx").on(table.status, table.createdAt),
    index("openreceive_payments_client_ip_inserted_idx").on(table.clientIp, table.insertedAt),
  ],
);

// The durable reconcile gate every worker on this database shares
// (key/value/rev compare-and-set). Same host database, never a second one.
export const openReceiveMeta = sqliteTable("openreceive_meta", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  rev: integer("rev").notNull().default(0),
});
`
    : `${header}import { ${pgImports(options)} } from "drizzle-orm/pg-core";
${ordersImportNote}
export const openReceivePayments = pgTable(
  "openreceive_payments",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
    ${orderIdLine}
    paymentHash: text("payment_hash").notNull(),
    status: text("status").notNull().default("pending"),
    statusReason: text("status_reason"),
    paidAt: bigint("paid_at", { mode: "number" }),
    expiresAt: bigint("expires_at", { mode: "number" }).notNull(),
    createdAt: bigint("created_at", { mode: "number" }).notNull(),
    updatedAt: bigint("updated_at", { mode: "number" }).notNull(),
    insertedAt: bigint("inserted_at", { mode: "number" }).notNull(),
    checkoutData: text("checkout_data").notNull(),
    swapData: text("swap_data"),
    clientIp: text("client_ip"),
  },
  (table) => [
    uniqueIndex("openreceive_payments_hash_uidx").on(table.paymentHash),
    index("openreceive_payments_order_created_idx").on(table.orderId, table.createdAt),
    index("openreceive_payments_status_created_idx").on(table.status, table.createdAt),
    index("openreceive_payments_client_ip_inserted_idx").on(table.clientIp, table.insertedAt),
  ],
);

// The durable reconcile gate every worker on this database shares
// (key/value/rev compare-and-set). Same host database, never a second one.
export const openReceiveMeta = pgTable("openreceive_meta", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  rev: bigint("rev", { mode: "number" }).notNull().default(0),
});
`;

  return [
    { path: "src/db/openreceive-tables.ts", contents: schema },
    { path: "OPENRECEIVE_PAYMENTS.md", contents: wiringGuideMarkdown(options) },
  ];
}

function pgImports(options: ScaffoldPaymentsOptions): string {
  const names = new Set(["bigint", "index", "pgTable", "text", "uniqueIndex"]);
  if (options.orderIdType === "integer") names.add("integer");
  if (options.orderIdType === "uuid") names.add("uuid");
  return [...names].sort((left, right) => left.localeCompare(right)).join(", ");
}

function camel(table: string): string {
  return table.replace(/_([a-z])/g, (_, letter: string) => letter.toUpperCase());
}
