import {
  fulfillmentNote,
  paymentsHashCheckSql,
  paymentsIndexName,
  paymentsStatusCheckSql,
} from "@openreceive/core";
import { isSqlite } from "../shared.ts";
import type { ScaffoldFile, ScaffoldPaymentsOptions } from "../types.ts";
import { wiringGuideMarkdown } from "../wiring-guide.ts";

export function renderDrizzleFiles(options: ScaffoldPaymentsOptions): ScaffoldFile[] {
  const sqlite = isSqlite(options);
  const table = options.tableName;
  const referenceLine = `reference: text("reference").notNull(),`;
  const indexName = (suffix: string): string => paymentsIndexName(table, suffix);
  const constraints = [
    `    uniqueIndex("${indexName("hash_uidx")}").on(table.paymentHash),`,
    `    index("${indexName("reference_created_idx")}").on(table.reference, table.createdAt),`,
    `    index("${indexName("status_created_idx")}").on(table.status, table.createdAt),`,
    `    index("${indexName("client_ip_inserted_idx")}").on(table.clientIp, table.insertedAt),`,
    // Both canonical CHECK constraints, so drizzle-kit migrations enforce the
    // same row shape the library's repository relies on.
    `    check("${indexName("status_check")}", sql\`${paymentsStatusCheckSql()}\`),`,
    `    check("${indexName("hash_check")}", sql\`${paymentsHashCheckSql(options.dialect)}\`),`,
  ].join("\n");

  const header = `// Generated by \`npx openreceive scaffold payments\` — schema only.
// OpenReceive owns the payment-attempt repository at runtime
// (createHost in @openreceive/http); these two tables exist so
// \`drizzle-kit generate\` creates the canonical DDL. Keep every column and
// CHECK constraint. Timestamps are unix-seconds integer columns, on purpose.
// The schema_version seed row cannot be expressed here — the wiring guide's
// migration step adds it as a custom migration.
//
${fulfillmentNote("// ", options.tableName)}
import { sql } from "drizzle-orm";
`;

  const schema = sqlite
    ? `${header}import { check, index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const payments = sqliteTable(
  "${table}",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    ${referenceLine}
    paymentHash: text("payment_hash").notNull(),
    status: text("status").notNull().default("pending"),
    statusReason: text("status_reason"),
    paidAt: integer("paid_at"),
    expiresAt: integer("expires_at").notNull(),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
    insertedAt: integer("inserted_at").notNull(),
    checkoutData: text("checkout_data").notNull(),
    swapData: text("swap_data"),
    clientIp: text("client_ip"),
  },
  (table) => [
${constraints}
  ],
);

// The durable reconcile gate every worker on this database shares
// (key/value/rev compare-and-set). Same host database, never a second one.
export const meta = sqliteTable("${options.metaTableName}", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  rev: integer("rev").notNull().default(0),
});
`
    : `${header}import { ${pgImports()} } from "drizzle-orm/pg-core";

export const payments = pgTable(
  "${table}",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
    ${referenceLine}
    paymentHash: text("payment_hash").notNull(),
    status: text("status").notNull().default("pending"),
    statusReason: text("status_reason"),
    paidAt: bigint("paid_at", { mode: "number" }),
    expiresAt: bigint("expires_at", { mode: "number" }).notNull(),
    createdAt: bigint("created_at", { mode: "number" }).notNull(),
    updatedAt: bigint("updated_at", { mode: "number" }).notNull(),
    insertedAt: bigint("inserted_at", { mode: "number" }).notNull(),
    checkoutData: text("checkout_data").notNull(),
    swapData: text("swap_data"),
    clientIp: text("client_ip"),
  },
  (table) => [
${constraints}
  ],
);

// The durable reconcile gate every worker on this database shares
// (key/value/rev compare-and-set). Same host database, never a second one.
export const meta = pgTable("${options.metaTableName}", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  rev: bigint("rev", { mode: "number" }).notNull().default(0),
});
`;

  return [
    { path: "src/db/openreceive-tables.ts", contents: schema },
    { path: "OPENRECEIVE_PAYMENTS.md", contents: wiringGuideMarkdown(options) },
  ];
}

function pgImports(): string {
  return ["bigint", "check", "index", "pgTable", "text", "uniqueIndex"].join(", ");
}
