import { knexOrderIdColumn } from "../shared.ts";
import type { ScaffoldFile, ScaffoldPaymentsOptions } from "../types.ts";
import { wiringGuideMarkdown } from "../wiring-guide.ts";

export function renderKnexFiles(options: ScaffoldPaymentsOptions): ScaffoldFile[] {
  const foreignKey = options.skipForeignKey
    ? ""
    : `\n      .references("id")\n      .inTable("${options.orderTable}")\n      .onDelete("RESTRICT")`;

  const migration = `/**
 * Generated by \`npx openreceive scaffold payments\` — migration only.
 * Creates both canonical OpenReceive tables: \`openreceive_payments\` and the
 * \`openreceive_meta\` reconcile gate. OpenReceive owns the payment-attempt
 * repository at runtime (createOpenReceiveHost in @openreceive/http), so no
 * repository code is generated. Keep every column; timestamps are unix-seconds
 * integer columns, on purpose.
 *
 * Dialect: ${options.dialect}
 */

/** @param {import("knex").Knex} knex */
export async function up(knex) {
  await knex.schema.createTable("openreceive_payments", (table) => {
    table.bigIncrements("id").primary();
    ${knexOrderIdColumn(options.orderIdType)}${foreignKey};
    table.text("payment_hash").notNullable().unique();
    table.text("status").notNullable().defaultTo("pending");
    table.text("status_reason").nullable();
    table.bigInteger("paid_at").nullable();
    table.bigInteger("expires_at").notNullable();
    table.bigInteger("created_at").notNullable();
    table.bigInteger("updated_at").notNullable();
    table.bigInteger("inserted_at").notNullable();
    table.text("checkout_data").notNullable();
    table.text("swap_data").nullable();
    table.text("client_ip").nullable();
    table.index(["order_id", "created_at"], "openreceive_payments_order_created_idx");
    table.index(["status", "created_at"], "openreceive_payments_status_created_idx");
    table.index(["client_ip", "inserted_at"], "openreceive_payments_client_ip_inserted_idx");
  });
  // The durable reconcile gate every worker on this database shares
  // (key/value/rev compare-and-set). Same host database, never a second one.
  await knex.schema.createTable("openreceive_meta", (table) => {
    table.text("key").primary();
    table.text("value").notNullable();
    table.bigInteger("rev").notNullable().defaultTo(0);
  });
}

/** @param {import("knex").Knex} knex */
export async function down(knex) {
  await knex.schema.dropTable("openreceive_meta");
  await knex.schema.dropTable("openreceive_payments");
}
`;

  return [
    {
      // .mjs: the migration uses ESM syntax, which a "type": "commonjs" host
      // would reject in a .js file. Knex loads .mjs migrations natively.
      path: "db/migrations/20260101000000_create_openreceive_tables.mjs",
      contents: migration,
    },
    { path: "OPENRECEIVE_PAYMENTS.md", contents: wiringGuideMarkdown(options) },
  ];
}
