import { fulfillmentNote } from "@openreceive/core";
import { canonicalPaymentsDdlStatements } from "../shared.ts";
import type { ScaffoldFile, ScaffoldPaymentsOptions } from "../types.ts";
import { wiringGuideMarkdown } from "../wiring-guide.ts";

export function renderKnexFiles(options: ScaffoldPaymentsOptions): ScaffoldFile[] {
  // Raw canonical DDL: Knex's schema builder cannot express the table-level
  // CHECK constraints portably, and knex.raw keeps this migration pinned to
  // the exact statements the library's repository expects — CHECKs and the
  // schema_version seed row included.
  const body = canonicalPaymentsDdlStatements(options)
    .map((statement) => `  await knex.raw(\`${statement}\`);`)
    .join("\n");

  const migration = `/**
 * Generated by \`npx openreceive scaffold payments\` — migration only.
 * Executes the canonical OpenReceive DDL: \`${options.tableName}\` and the
 * \`${options.metaTableName}\` reconcile gate, CHECK constraints and the
 * schema_version seed row included. OpenReceive owns the payment-attempt
 * repository at runtime (createHost in @openreceive/http), so no
 * repository code is generated. Keep every column and constraint; timestamps
 * are unix-seconds integer columns, on purpose.
 *
 * Dialect: ${options.dialect}
 *
${fulfillmentNote(" * ", options.tableName)}
 */

/** @param {import("knex").Knex} knex */
export async function up(knex) {
${body}
}

/** @param {import("knex").Knex} knex */
export async function down(knex) {
  await knex.raw("DROP TABLE IF EXISTS ${options.metaTableName}");
  await knex.raw("DROP TABLE IF EXISTS ${options.tableName}");
}
`;

  return [
    {
      // .mjs: the migration uses ESM syntax, which a "type": "commonjs" host
      // would reject in a .js file. Knex loads .mjs migrations natively.
      path: "db/migrations/20260101000000_create_openreceive_tables.mjs",
      contents: migration,
    },
    { path: "OPENRECEIVE_PAYMENTS.md", contents: wiringGuideMarkdown(options) },
  ];
}
