import {
  fulfillmentNote,
  paymentsHashCheckSql,
  paymentsIndexName,
  paymentsSeedSql,
  paymentsStatusCheckSql,
} from "@openreceive/core";
import { isSqlite } from "../shared.ts";
import type { ScaffoldFile, ScaffoldPaymentsOptions } from "../types.ts";
import { wiringGuideMarkdown } from "../wiring-guide.ts";

export function renderPrismaFiles(options: ScaffoldPaymentsOptions): ScaffoldFile[] {
  const idField = isSqlite(options)
    ? "Int     @id @default(autoincrement())"
    : "BigInt  @id @default(autoincrement())";
  const schema = `// Generated by \`npx openreceive scaffold payments\` — schema only.
// OpenReceive owns the payment-attempt repository at runtime
// (createHost in @openreceive/http); these two models exist so
// \`prisma migrate\` creates the canonical tables. Keep every column.
// Timestamps are unix-seconds integer columns (BigInt), on purpose.
//
// Prisma's schema language cannot express the canonical CHECK constraints or
// the schema_version seed row: apply prisma/openreceive-constraints.sql as
// described in OPENRECEIVE_PAYMENTS.md when creating the migration.
//
// Merge both models into your Prisma schema, then run:
//   npx prisma migrate dev --create-only --name create_openreceive_tables
//
// Dialect: ${options.dialect}
//
${fulfillmentNote("// ", options.tableName)}

model OpenReceivePayment {
  id           ${idField}
  orderId      String  @map("order_id")
  paymentHash  String  @unique @map("payment_hash")
  status       String  @default("pending")
  statusReason String? @map("status_reason")
  paidAt       BigInt? @map("paid_at")
  expiresAt    BigInt  @map("expires_at")
  createdAt    BigInt  @map("created_at")
  updatedAt    BigInt  @map("updated_at")
  insertedAt   BigInt  @map("inserted_at")
  checkoutData String  @map("checkout_data")
  swapData     String? @map("swap_data")
  clientIp     String? @map("client_ip")

  @@index([orderId, createdAt])
  @@index([status, createdAt])
  @@index([clientIp, insertedAt])
  @@map("${options.tableName}")
}

// The durable reconcile gate every worker on this database shares (key/value/rev
// compare-and-set). Same host database as ${options.tableName}.
model OpenReceiveMeta {
  key   String @id
  value String
  rev   BigInt @default(0)

  @@map("${options.metaTableName}")
}
`;

  return [
    { path: "prisma/schema.openreceive.prisma", contents: schema },
    { path: "prisma/openreceive-constraints.sql", contents: constraintsSql(options) },
    { path: "OPENRECEIVE_PAYMENTS.md", contents: wiringGuideMarkdown(options) },
  ];
}

/**
 * The canonical CHECK constraints and the schema_version seed row, which
 * Prisma's schema language cannot express. The host applies this to the draft
 * migration created with `prisma migrate dev --create-only`.
 */
function constraintsSql(options: ScaffoldPaymentsOptions): string {
  const statusCheck = paymentsStatusCheckSql();
  const hashCheck = paymentsHashCheckSql(options.dialect);
  const seed = paymentsSeedSql(options.dialect, options.metaTableName);
  if (options.dialect === "postgres") {
    return `-- Generated by \`npx openreceive scaffold payments\`.
-- Prisma's schema language cannot express these; append this file to the draft
-- migration created by \`npx prisma migrate dev --create-only\` before applying.
ALTER TABLE "${options.tableName}" ADD CONSTRAINT "${paymentsIndexName(options.tableName, "status_check")}" CHECK (${statusCheck});
ALTER TABLE "${options.tableName}" ADD CONSTRAINT "${paymentsIndexName(options.tableName, "hash_check")}" CHECK (${hashCheck});
${seed};
`;
  }
  return `-- Generated by \`npx openreceive scaffold payments\`.
-- Prisma's schema language cannot express these, and sqlite cannot ALTER TABLE
-- ... ADD CHECK. After \`npx prisma migrate dev --create-only\`, edit the draft
-- migration: paste the two CHECK lines below into the
-- CREATE TABLE "${options.tableName}" (...) column list, then append the INSERT.
--
--   CHECK (${statusCheck}),
--   CHECK (${hashCheck})
--
${seed};
`;
}
