import { isSqlite, prismaOrderIdField } from "../shared.ts";
import type { ScaffoldFile, ScaffoldPaymentsOptions } from "../types.ts";
import { wiringGuideMarkdown } from "../wiring-guide.ts";

export function renderPrismaFiles(options: ScaffoldPaymentsOptions): ScaffoldFile[] {
  const idField = isSqlite(options)
    ? "Int     @id @default(autoincrement())"
    : "BigInt  @id @default(autoincrement())";
  const relation = options.skipForeignKey
    ? ""
    : `  order        ${options.orderModel} @relation(fields: [orderId], references: [id], onDelete: Restrict)\n`;
  const relationNote = options.skipForeignKey
    ? ""
    : `//
// Add the back-relation to your ${options.orderModel} model:
//   openReceivePayments OpenReceivePayment[]
`;

  const schema = `// Generated by \`npx openreceive scaffold payments\` — schema only.
// OpenReceive owns the payment-attempt repository at runtime
// (createOpenReceiveHost in @openreceive/http); these two models exist so
// \`prisma migrate\` creates the canonical tables. Keep every column.
// Timestamps are unix-seconds integer columns (BigInt), on purpose.
//
// Merge both models into your Prisma schema, then run:
//   npx prisma migrate dev --name create_openreceive_tables
//
// Dialect: ${options.dialect}
${relationNote}
model OpenReceivePayment {
  id           ${idField}
  orderId      ${prismaOrderIdField(options.orderIdType, options.dialect)}
${relation}  paymentHash  String  @unique @map("payment_hash")
  status       String  @default("pending")
  statusReason String? @map("status_reason")
  paidAt       BigInt? @map("paid_at")
  expiresAt    BigInt  @map("expires_at")
  createdAt    BigInt  @map("created_at")
  updatedAt    BigInt  @map("updated_at")
  insertedAt   BigInt  @map("inserted_at")
  checkoutData String  @map("checkout_data")
  swapData     String? @map("swap_data")
  clientIp     String? @map("client_ip")

  @@index([orderId, createdAt])
  @@index([status, createdAt])
  @@index([clientIp, insertedAt])
  @@map("openreceive_payments")
}

// The durable reconcile gate every worker on this database shares (key/value/rev
// compare-and-set). Same host database as openreceive_payments.
model OpenReceiveMeta {
  key   String @id
  value String
  rev   BigInt @default(0)

  @@map("openreceive_meta")
}
`;

  return [
    { path: "prisma/schema.openreceive.prisma", contents: schema },
    { path: "OPENRECEIVE_PAYMENTS.md", contents: wiringGuideMarkdown(options) },
  ];
}
