import { sequelizeOrderIdType } from "../shared.ts";
import type { ScaffoldFile, ScaffoldPaymentsOptions } from "../types.ts";
import { wiringGuideMarkdown } from "../wiring-guide.ts";

export function renderSequelizeFiles(options: ScaffoldPaymentsOptions): ScaffoldFile[] {
  const references = options.skipForeignKey
    ? ""
    : `
        references: { model: "${options.orderTable}", key: "id" },
        onDelete: "RESTRICT",`;

  const migration = `"use strict";

/**
 * Generated by \`npx openreceive scaffold payments\` — migration only.
 * Creates both canonical OpenReceive tables: \`openreceive_payments\` and the
 * \`openreceive_meta\` reconcile gate. OpenReceive owns the payment-attempt
 * repository at runtime (createOpenReceiveHost in @openreceive/http), so no
 * model or repository code is generated. Keep every column; timestamps are
 * unix-seconds integer columns, on purpose.
 *
 * Dialect: ${options.dialect}
 */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.createTable("openreceive_payments", {
      id: { type: Sequelize.BIGINT, autoIncrement: true, primaryKey: true },
      order_id: {
        type: ${sequelizeOrderIdType(options.orderIdType)},
        allowNull: false,${references}
      },
      payment_hash: { type: Sequelize.TEXT, allowNull: false, unique: true },
      status: { type: Sequelize.TEXT, allowNull: false, defaultValue: "pending" },
      status_reason: { type: Sequelize.TEXT, allowNull: true },
      paid_at: { type: Sequelize.BIGINT, allowNull: true },
      expires_at: { type: Sequelize.BIGINT, allowNull: false },
      created_at: { type: Sequelize.BIGINT, allowNull: false },
      updated_at: { type: Sequelize.BIGINT, allowNull: false },
      inserted_at: { type: Sequelize.BIGINT, allowNull: false },
      checkout_data: { type: Sequelize.TEXT, allowNull: false },
      swap_data: { type: Sequelize.TEXT, allowNull: true },
      client_ip: { type: Sequelize.TEXT, allowNull: true },
    });
    await queryInterface.addIndex("openreceive_payments", ["order_id", "created_at"], {
      name: "openreceive_payments_order_created_idx",
    });
    await queryInterface.addIndex("openreceive_payments", ["status", "created_at"], {
      name: "openreceive_payments_status_created_idx",
    });
    await queryInterface.addIndex("openreceive_payments", ["client_ip", "inserted_at"], {
      name: "openreceive_payments_client_ip_inserted_idx",
    });
    // The durable reconcile gate every worker on this database shares
    // (key/value/rev compare-and-set). Same host database, never a second one.
    await queryInterface.createTable("openreceive_meta", {
      key: { type: Sequelize.TEXT, primaryKey: true },
      value: { type: Sequelize.TEXT, allowNull: false },
      rev: { type: Sequelize.BIGINT, allowNull: false, defaultValue: 0 },
    });
  },

  async down(queryInterface) {
    await queryInterface.dropTable("openreceive_meta");
    await queryInterface.dropTable("openreceive_payments");
  },
};
`;

  return [
    {
      // .cjs: the migration uses module.exports, which a "type": "module" host
      // would reject in a .js file. sequelize-cli loads .cjs migrations natively.
      path: "migrations/20260101000000-create-openreceive-tables.cjs",
      contents: migration,
    },
    { path: "OPENRECEIVE_PAYMENTS.md", contents: wiringGuideMarkdown(options) },
  ];
}
