import { fulfillmentNote } from "@openreceive/core";
import { canonicalPaymentsDdlStatements } from "../shared.ts";
import type { ScaffoldFile, ScaffoldPaymentsOptions } from "../types.ts";
import { wiringGuideMarkdown } from "../wiring-guide.ts";

export function renderSequelizeFiles(options: ScaffoldPaymentsOptions): ScaffoldFile[] {
  // Raw canonical DDL: queryInterface.createTable cannot express the
  // table-level CHECK constraints or the schema_version seed row, and raw SQL
  // keeps this migration pinned to the exact statements the library's
  // repository expects.
  const body = canonicalPaymentsDdlStatements(options)
    .map((statement) => `    await queryInterface.sequelize.query(\`${statement}\`);`)
    .join("\n");

  const migration = `"use strict";

/**
 * Generated by \`npx openreceive scaffold payments\` — migration only.
 * Executes the canonical OpenReceive DDL: \`${options.tableName}\` and the
 * \`${options.metaTableName}\` reconcile gate, CHECK constraints and the
 * schema_version seed row included. OpenReceive owns the payment-attempt
 * repository at runtime (createHost in @openreceive/http), so no
 * model or repository code is generated. Keep every column and constraint;
 * timestamps are unix-seconds integer columns, on purpose.
 *
 * Dialect: ${options.dialect}
 *
${fulfillmentNote(" * ", options.tableName)}
 */
module.exports = {
  async up(queryInterface) {
${body}
  },

  async down(queryInterface) {
    await queryInterface.sequelize.query("DROP TABLE IF EXISTS ${options.metaTableName}");
    await queryInterface.sequelize.query("DROP TABLE IF EXISTS ${options.tableName}");
  },
};
`;

  return [
    {
      // .cjs: the migration uses module.exports, which a "type": "module" host
      // would reject in a .js file. sequelize-cli loads .cjs migrations natively.
      path: "migrations/20260101000000-create-openreceive-tables.cjs",
      contents: migration,
    },
    { path: "OPENRECEIVE_PAYMENTS.md", contents: wiringGuideMarkdown(options) },
  ];
}
