import { openReceiveFulfillmentNote } from "@openreceive/core";
import { canonicalPaymentsDdlStatements } from "../shared.ts";
import type { ScaffoldFile, ScaffoldPaymentsOptions } from "../types.ts";
import { wiringGuideMarkdown } from "../wiring-guide.ts";

export function renderTypeOrmFiles(options: ScaffoldPaymentsOptions): ScaffoldFile[] {
  const body = canonicalPaymentsDdlStatements(options)
    .map((statement) => `    await queryRunner.query(\`${statement}\`);`)
    .join("\n");

  const migration = `// Generated by \`npx openreceive scaffold payments\` — migration only.
// Executes the canonical OpenReceive DDL: \`${options.tableName}\` and the
// \`${options.metaTableName}\` reconcile gate, both tables in this one migration.
// OpenReceive owns the payment-attempt repository at runtime
// (createOpenReceiveHost in @openreceive/http), so there is no entity class to
// register. Keep every column; timestamps are unix-seconds integer columns, on
// purpose.
//
${openReceiveFulfillmentNote("// ", options.tableName)}
import type { MigrationInterface, QueryRunner } from "typeorm";

export class CreateOpenReceiveTables20260101000000 implements MigrationInterface {
  name = "CreateOpenReceiveTables20260101000000";

  public async up(queryRunner: QueryRunner): Promise<void> {
${body}
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("DROP TABLE IF EXISTS ${options.metaTableName}");
    await queryRunner.query("DROP TABLE IF EXISTS ${options.tableName}");
  }
}
`;

  return [
    {
      path: "src/migrations/20260101000000-create-openreceive-tables.ts",
      contents: migration,
    },
    { path: "OPENRECEIVE_PAYMENTS.md", contents: wiringGuideMarkdown(options) },
  ];
}
