import { readdir } from "node:fs/promises";
import path from "node:path";
import { fulfillmentNoteMarkdown, supabasePaymentsMigrationSql } from "@openreceive/core";
import type { ScaffoldFile } from "./types.ts";

// `openreceive scaffold payments --supabase`: one Supabase migration (the
// tables, locked away from the Data API, plus the functions the HTTPS
// repository calls) and a wiring guide. For servers that reach Supabase over
// its HTTPS API: Cloudflare Workers and Lovable, which cannot open a Postgres
// connection to it.

const MIGRATIONS_DIR = "supabase/migrations";
const MIGRATION_SUFFIX = "_openreceive.sql";

/** Supabase CLI migration names start with a 14-digit UTC timestamp. */
function migrationTimestamp(now: Date): string {
  return now.toISOString().replace(/\D/g, "").slice(0, 14);
}

/**
 * The migration's path under the output root: the one already there (so
 * `--force` rewrites it instead of adding a second), or a new one stamped now.
 */
export async function supabaseMigrationPath(root: string, now: Date): Promise<string> {
  let names: string[] = [];
  try {
    names = await readdir(path.join(root, MIGRATIONS_DIR));
  } catch {
    // No migrations folder yet: the writer creates it.
  }
  const existing = names.filter((name) => /^\d+_openreceive\.sql$/.test(name)).sort()[0];
  return `${MIGRATIONS_DIR}/${existing ?? `${migrationTimestamp(now)}${MIGRATION_SUFFIX}`}`;
}

export function renderSupabaseFiles(migrationPath: string): ScaffoldFile[] {
  return [
    { path: migrationPath, contents: supabasePaymentsMigrationSql() },
    { path: "OPENRECEIVE_PAYMENTS.md", contents: supabaseGuideMarkdown(migrationPath) },
  ];
}

function supabaseGuideMarkdown(migrationPath: string): string {
  return `# OpenReceive payments on Supabase

Generated by \`openreceive scaffold payments --supabase\`. It wrote one migration,
\`${migrationPath}\`, and this guide. Your server reaches Supabase over its
HTTPS API with the project's secret key, so this works where a Postgres
connection to Supabase cannot: Cloudflare Workers, including Lovable's apps.
The OpenReceive library owns the payment-attempt logic at runtime; the
migration holds only the tables and the functions that lock each order while
they write.

## 1. Apply the migration

\`supabase db push\`, or paste the file into the SQL Editor and run it. It
creates \`openreceive_payments\` and \`openreceive_meta\`, turns on row level
security, and revokes every grant from \`anon\` and \`authenticated\`: the Data
API's public roles must never read \`swap_data\` or mark an order paid. Only the
server key can call OpenReceive's functions. Applying it again is safe.

## 2. Write \`openreceive_on_paid\`

The migration created \`public.openreceive_on_paid\` as a placeholder that
refuses every settlement. Replace it in a migration of your own, after the
scaffold's, with the SQL that marks your order paid:

\`\`\`sql
create or replace function public.openreceive_on_paid(
  p_reference text, p_payment_hash text, p_paid_at bigint
) returns void language plpgsql as $$
begin
  update public.orders
     set status = 'paid'
   where id = p_reference::uuid   -- or just p_reference, if your ids are text
     and status = 'pending';
end
$$;
\`\`\`

It runs inside the settlement transaction, for the first settled attempt for
a reference only. If it raises, nothing is recorded: the attempt stays
pending, and the next reconcile pass tries again. No payment is lost.

\`create or replace\` keeps the function private. If you ever drop and create
it instead, run these again, because whoever can call it can mark an order
paid:

\`\`\`sql
revoke execute on function public.openreceive_on_paid(text, text, bigint) from public, anon, authenticated;
grant execute on function public.openreceive_on_paid(text, text, bigint) to service_role;
\`\`\`

## 3. Wire the server

\`\`\`ts
import { createStack } from "@openreceive/http";

const stack = createStack({
  wallet: { nwc: env.NWC_URI },
  storage: {
    supabase: { url: env.SUPABASE_URL, key: env.SUPABASE_SERVICE_ROLE_KEY },
  },
  amountFor,
  authorize,
});
\`\`\`

- \`key\` is the project's secret key (\`sb_secret_…\`) or its legacy
  \`service_role\` key. It stays on the server: never in a \`VITE_\` or
  \`NEXT_PUBLIC_\` variable, browser code or logs.
- There is no \`onPaid\` here; \`openreceive_on_paid\` is your fulfillment.
- On Cloudflare Workers, build the stack per request and close it when the
  request is done.

Before it serves, the server checks the database: the functions are this
library's version, \`openreceive_on_paid\` is yours and not the placeholder,
row level security is on, and \`anon\` and \`authenticated\` reach nothing. If
any of that fails, the payment routes answer 503 and the log names the fix.

## 4. Fulfilling exactly once

${fulfillmentNoteMarkdown("openreceive_payments")}

In this project's terms, the guarded write is \`openreceive_on_paid\`, and it
already runs in OpenReceive's settlement transaction. Its \`WHERE status =
'pending'\` is the guard: a later call updates nothing.

Never expose \`swap_data\` from application APIs, logs, or browser bundles.
`;
}
